### PR TITLE
Nuget

### PR DESCRIPTION
**Pull request by nickntg**
This might help to get started with nuget (see #46).

Before being able to run publish_nuget.cmd you'll need to create an account in nuget.org.

### CODE REVIEW

**Comment by aalhour** [comment]
Hi @nickntg,

Thanks for the addition. Please read the [CONTRIBUTING Guide](https://github.com/aalhour/C-Sharp-Algorithms/blob/master/CONTRIBUTING.md) before submitting Pull Requests. There should be an issue for any proposed change. Ideally, we will discuss the issue there first and then move to a pull request.

**Comment by PatrykOlejniczak** [comment]
Hello @nickntg 

Can you split this into 2 separate pr one for nuget and other one for Primes list fix?

Greetings

**Comment by nickntg** [comment]
Yeah, I can do that. I did that in order to ensure that everything stays packed in the library and there is no need to add the data folder in the nuget. Still want me to do it?

**Comment by aalhour** [comment]
Hi @nickntg,

I think what @PatrykOlejniczak meant is that it would be better to have one separate PR for the Primes fix and another PR for the Nuget Spec. Two PRs in total. One for each change. Could you please do that? We can keep this PR for the Primes fix so you only have to move the Nuget Spec into a new separate PR.

Cheers,
Ahmad

**Comment by PatrykOlejniczak** [comment]
Yea, i meant, one pr = one change (one issue), just to make pr small/easy to review :)

**Comment by aalhour** [comment]
@nickntg - any updated from your side?

**Comment by nickntg** [comment]
@aalhour Sure, will do and submit new PRs.

**Comment by aalhour** [comment]
@nickntg - now that #124 is merged, please clean up this PR and make sure it only contains the changes relevant to Nuget publishing.

**Comment by nickntg** [comment]
@aalhour Done. However, this works on windows machines only...

**Pull request merged**
