### PR TITLE
[UnitTest/Framework] - Refactoring Unit-Tests / Switching to .Net Core

### PR DESCRIPTION
**Pull request by ivandrofly**
# ⚠️  Under Construction ⛑

## TODOS:

- [x] Change Algorithms project to **.net core**
- [x] Change DataStructures projects to **.net core**
- [x] Remove "MainProgram" test.

## Algorithms Tests

- [x] BinarySearchTreeSorterTest
- [x] BinaryTreeRecursiveWalkerTests
- [x] CatalanNumbersTest
- [x] CountingSortTest
- [ ] GraphsBellmanFordShortestPaths
- [x] GraphsBipartiteColoringTest
- [ ] GraphsBreadthFirstPathsTest
- [x] GraphsBreadthFirstSearchTest
- [ ] GraphsConnectedComponents
- [x] GraphsCyclesDetectorTests
- [ ] GraphsDepthFirstSearchTest
- [x] GraphsDijkstraShortestPathsTest
- [ ] GraphsTopologicalSorterTest
- [x] GreatestCommonDivisorTest
- [x] HeapSorterTest
- [x] InsertionSortTest
- [x] LSDRadixSorterTest
- [x] MergeSorterTest
- [x] QuickSortTest
- [x] StringEditDistanceTest
- [x] StringPermutationTests

## Data Structures Tests

- [x] ArrayListTest
- [x] AVLTreeTest
- [x] BinaryHeapsTest
- [x] BinarySearchTreeMapTests
- [x] BinarySearchTreeTest
- [x] BinomialHeapsTest
- [ ] CliqueGraphTest
- [x] CuckooHashTableTest
- [x] DLinkedListTest
- [x] GraphsDirectedDenseGraphTest
- [x] GraphsDirectedSparseGraphTest
- [ ] GraphsDirectedWeightedDenseGraphTest
- [ ] GraphsDirectedWeightedSparseGraphTest
- [x] GraphsUndirectedDenseGraphTest
- [x] GraphsUndirectedSparseGraphTest
- [x] GraphsUndirectedWeightedDenseGraphTest
- [x] GraphsUndirectedWeightedSparseGraphTest
- [x] HashTableSeparateChainingTest
- [x] PriorityQueuesTest
- [x] QueueTest
- [x] RedBlackTreeMapTests
- [x] RedBlackTreeTest ⚠️ 
- [x] SkipListTest
- [x] SLinkedListTest
- [x] SortedDictionaryTests
- [x] SortedListTests
- [x] StackTest
- [x] TrieMapTest
- [x] TrieTest

## Misc
- [x] Fix broken codes and cleanup
- [ ] Ready for merge

## Framework changes:

```c#
ApplicationException => InvalidOperationException
Assembly.GetExecutingAssembly().Location => typeof(PrimesList).GetTypeInfo().Assembly.Location
```

### CODE REVIEW

**Comment by ivandrofly** [comment]
I have been very lately... next week I'll continue coding this patch 😉 /cc @aalhour

**Comment by aalhour** [comment]
Hey @ivandrofly, sure thing, no worries 😉

**Comment by ivandrofly** [comment]
Seems like we are having conflicts with this branch...

**Comment by ivandrofly** [comment]
Couple more then we finish... :)

PS: The conflicts also need to be resolved

**Comment by aalhour** [comment]
Hello @ivandrofly, I have just merged PR #49, it might cause some problems with your migration. Can you take a look at it when you're done?

**Comment by ivandrofly** [comment]
I have rebased and fixed most of the problem... I think this branch is ready to be merged and the remaining tests can be send in separated PR in order to avoid more merge conflicts in future. /cc @aalhour 

PS: I have some modified files (locally) which can cause some red squiggly in VS after merged with master branch, that will be fixed in next PR.

**Comment by aalhour** [comment]
Hello @ivandrofly,

Sorry for the late reply, I was very busy lately. This sounds good to me. I will merge it now and will be waiting for your next PR.

Cheers,
Ahmad

**Pull request merged**
