### PR TITLE
Fixing broken tests

### PR DESCRIPTION
**Pull request by hbsock**
Fixing broken tests on SortedDictionaryTests and DLinkedListTest

### CODE REVIEW

**Comment by ivandrofly** [comment]
I'd recommend to keep this on hold until #38 is finished

**Comment by hbsock** [comment]
Alright. Is there a way for me to label this pull request on hold?

**Comment by ivandrofly** [comment]
> Alright. Is there a way for me to label this pull request on hold?

/cc @aalhour

**Comment by aalhour** [comment]
Hello @hbsock,

The migration of the tests package to use a unit testing framework is done, can you please resolve the merge conflicts that you have in this PR?

Cheers,
Ahmad

**Comment by hbsock** [comment]
Sure.

**Comment by hbsock** [comment]
It seems the unit tests for SortedDictionaryTests already had the changes I originally had, so I only updated the DLinkedListTest.

**Comment by aalhour** [comment]
Hello @hbsock,

Can you please try to rebase your branch once more against master? I have fixed the issue causing the Travis builds to fail.

Cheers,
Ahmad

**Comment by hbsock** [comment]
Sure.

**Comment by hbsock** [comment]
@aalhour could this PR be merged now?

Thank you.

**Comment by aalhour** [comment]
Absolutely. Thanks for contributing.

**Pull request merged**
