### PR TITLE
Removed redundant parameters and cleaned up code

### PR DESCRIPTION
**Pull request by scohe001**
**Change Notes for `MergeSorter.cs`:**
- The "base case" where the count of `collection` is 2 will already be handled properly if we let the collection be split and merged. There's no need to explicitly write a case for it.
- The parameters `startIndex` and `endIndex` are unneeded. `startIndex` will *always* be 0 and `endIndex` will *always* be `collection.Count - 1`. It seems someone started to write an in-place index-based MergeSort, but switched to one that splits and creates new Lists.
- Cleaned up the for loop in Merge with the strange break in the else. Updated the loop condition so that we don't even have to worry about that.
- At most one of the two split Lists will still have items after the initial loop in Merge (after all, we only stop looping after we've exhausted one List, so that List can't have any more items). As such, there's no need for separate right and left index variables. Cleaned up the ending loops with this in mind.

### CODE REVIEW

**Comment by aalhour** [comment]
Hi @scohe001,

Can you please pull the latest changes on `master` branch and push them to your repo? They're supposed to run the unit tests for all algorithms on Travis CI successfully and I'd like to see that the tests for the merge sort algorithm are passing.

Cheers!

**Comment by scohe001** [comment]
Huh, it looks like several tests are failing @aalhour, but none of them related to the code I've touched. Is this expected?

**Comment by aalhour** [comment]
Congrats on becoming a first-time contributor, @scohe001!

**Comment by scohe001** [comment]
Thank you! Glad I could help :)

**Pull request merged**
